# Default values for ims.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

auth_service_image:
  repository: localhost:5000/auth-service/auth-service
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

env:
  PORT: 5001
  DB_HOST: host.docker.internal
  DB_NAME: auth_service
  DB_PORT: 5432
  DB_USER: postgres
  DB_PASSWORD: root@123

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: auth.shaed.ai
      paths:
        - path: /
          pathType: Prefix
